### ISSUE TITLE
How tests change?

### ISSUE THREAD

**Issue by Slamdunk** [Ocramius/from-helpers-to-middleware#4]
There is one thing that I find it hard for some people to understand about testability.

When I test ZF2 bloated controllers ([this](https://github.com/Ocramius/from-helpers-to-middleware/blob/gh-pages/slides/from-helpers-to-middleware/zf2-and-decent-patterns/controller-3.html) and [this](https://github.com/Ocramius/from-helpers-to-middleware/blob/gh-pages/slides/from-helpers-to-middleware/zf2-and-decent-patterns/controller-4.html)) and code coverage is 100%, I am sure that every piece of code **and** every business logic is tested.

The other way can be sneaky and bastard: in a middleware stack line [this](https://github.com/Ocramius/from-helpers-to-middleware/tree/gh-pages/examples/middleware) I can reach 100% code-coverage, but I can mess the entire business logic up in factories while building the app. No type-hint forces me to delegate a middleware before another.

Can you pinpoint how tests have to adapt?

**Comment by Ocramius** [comment]
@Slamdunk business logic becomes responsible for things such as auth checks, but indeed, a failure to produce a proper validation message will lead to a validation error.

Either the code has to treat that, or it has to simply crash at runtime. This is described in the forelast slide (before the `thanks!`)

**Comment by Slamdunk** [comment]
~~I'm not sure I understand what you are saying~~
I'm sure I don't understand what you are saying
😕

**Comment by Ocramius** [comment]
> I can mess the entire business logic up in factories while building the app.

That's a bit that I clarified later during the conference call - the business logic, if correctly segregated in the business layer, has nothing to do with the HTTP layer.

If a constraint fails at business level, it causes an exception, which in turn causes a 5xx error in the frontend.

All of the HTTP middleware logic in the frontend is just providing "composition" for the frontend UX (nice error messages, redirects, etc).

An end to end test suite is highly needed, yes, and there's no way to avoid that anyway, with or without middleware.

**Comment by Slamdunk** [comment]
👍
